### ISSUE TITLE
Plugin doesn't respect .editorconfig sections

### ISSUE THREAD

**Issue by vrevelas** [ec4j/editorconfig-maven-plugin#41] opened 2019-08-20 10:04 UTC
If I have a .editorconfig file that looks like this
```
root = true

[*]
end_of_line = lf
insert_final_newline = true

[*.min.css]
insert_final_newline = unset
```

The plugin will still complain about minified css files not having a trailing newline. The order of the sections makes no difference. I'd expect it to prioritise any matching globs over the [*] global section.

**Comment by ppalaga** [comment] 2019-12-18 09:03
I tried to reproduce in my branch [i41](https://github.com/ppalaga/editorconfig-maven-plugin/tree/i41) where I have added your rule and two min.css files into one of the projects against which we run our integration tests. But everything seems to work properly there.

```
git clone git@github.com:ppalaga/editorconfig-maven-plugin.git
git checkout -b i41 origin/i41

cd src/test/projects/defaults

cat .editorconfig 
...
root = true

[*]
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2

[*.min.css]
insert_final_newline = unset


mvn mvn editorconfig:check
....
[INFO] --- editorconfig-maven-plugin:0.0.10:check (default-cli) @ defaults ---
[ERROR] src/main/resources/indent.xml@23,5: Delete 1 character - violates indent_style = space, indent_size = 2, reported by org.ec4j.linters.XmlLinter
[ERROR] src/main/resources/indent.xml@24,3: Delete 2 characters - violates indent_style = space, indent_size = 2, reported by org.ec4j.linters.XmlLinter
[ERROR] src/main/resources/trailing-whitespace.txt@1,7: Delete 2 characters - violates trim_trailing_whitespace = true, reported by org.ec4j.linters.TextLinter
[ERROR] README.adoc@2,1: Delete 2 characters - violates trim_trailing_whitespace = true, reported by org.ec4j.linters.TextLinter
[INFO] Checked 8 files
```

Note that no errors is reported for any of the two min.css files.

When I remove your rule from .editorconfig, the errors are reported:

```
...
[INFO] --- editorconfig-maven-plugin:0.0.10:check (default-cli) @ defaults ---
...
[ERROR] src/main/resources/style.min.css@1,85: Insert lf - violates insert_final_newline = true, reported by org.ec4j.linters.TextLinter
...
[ERROR] style.min.css@1,85: Insert lf - violates insert_final_newline = true, reported by org.ec4j.linters.TextLinter
[INFO] Checked 8 files
[
```

Could you please try to reproduce on your machine?

**Comment by ppalaga** [comment] 2019-12-23 08:18
Closing because I cannot reproduce. Feel free to reopen if you feel the problem persists.

**Closed by ppalaga** 2019-12-23 08:18 UTC
