### ISSUE TITLE
[Query] Editor Config Maven Plugin for Java

### ISSUE THREAD

**Issue by RmshVen** [ec4j/editorconfig-maven-plugin#66] opened 2022-05-31 21:40 UTC
Hi,

I have a question about the editor config maven plugin. I see the formatting works for .xml files, not for java. Please let me know if the plugin supports formatting the Java files.

**Comment by ppalaga** [comment] 2023-06-11 21:09
Duplicate of https://github.com/ec4j/editorconfig-linters/issues/23

**Closed by ppalaga** 2023-06-11 21:09 UTC
