### ISSUE TITLE
No support for java files

### ISSUE THREAD

**Issue by vemahendran** [ec4j/editorconfig-maven-plugin#120] opened 2023-06-10 14:15 UTC
I initially was impressed with this plugin and thought of adding it in our CI/CD pipelines. Eventually I figured out the support was available only for `.xml` files like `pom.xml`. It doesn't work on `*.java` files.

**Comment by ppalaga** [comment] 2023-06-11 21:09
Duplicate of https://github.com/ec4j/editorconfig-linters/issues/23

**Closed by ppalaga** 2023-06-11 21:09 UTC
